from typing import Any, Callable, Dict, List, Optional, Tuple, Union, TypeVar
from typing_extensions import ParamSpec, Literal
import bottle
import gevent

P = ParamSpec('P')
R = TypeVar('R')

class EelApplication:
    def __init__(self) -> None: ...
    def expose(self, name_or_function: Optional[Union[str, Callable[..., Any]]] = ...) -> Callable[..., Any]: ...
    def rate_limit(self, max_calls: int = ..., time_window: int = ...) -> Callable[..., Any]: ...
    def init(self, path: str, allowed_extensions: List[str] = ..., js_result_timeout: int = ...) -> None: ...
    def start(self, *start_urls: str, mode: str = ..., host: str = ..., port: int = ..., block: bool = ..., jinja_templates: str = ..., cmdline_args: List[str] = ..., size: Tuple[int, int] = ..., position: Tuple[int, int] = ..., geometry: Dict[str, Tuple[int, int]] = ..., close_callback: Callable = ..., app_mode: bool = ..., all_interfaces: bool = ..., disable_cache: bool = ..., default_path: str = ..., app: bottle.Bottle = ..., shutdown_delay: float = ..., suppress_error: bool = ...) -> None: ...
    def show(self, *start_urls: str) -> None: ...
    def sleep(self, seconds: Union[int, float]) -> None: ...
    def spawn(self, function: Callable[..., Any], *args: Any, **kwargs: Any) -> gevent.Greenlet: ...
    def register_eel_routes(self, app: bottle.Bottle) -> None: ...

_default_app: EelApplication

def init(path: str, allowed_extensions: List[str] = ..., js_result_timeout: int = ...) -> None: ...
def start(*start_urls: str, mode: str = ..., host: str = ..., port: int = ..., block: bool = ..., jinja_templates: str = ..., cmdline_args: List[str] = ..., size: Tuple[int, int] = ..., position: Tuple[int, int] = ..., geometry: Dict[str, Tuple[int, int]] = ..., close_callback: Callable = ..., app_mode: bool = ..., all_interfaces: bool = ..., disable_cache: bool = ..., default_path: str = ..., app: bottle.Bottle = ..., shutdown_delay: float = ..., suppress_error: bool = ...) -> None: ...
def expose(name_or_function: Optional[Union[str, Callable[..., Any]]] = ...) -> Callable[..., Any]: ...
def rate_limit(max_calls: int = ..., time_window: int = ...) -> Callable[..., Any]: ...
def sleep(seconds: Union[int, float]) -> None: ...
def spawn(function: Callable[..., Any], *args: Any, **kwargs: Any) -> gevent.Greenlet: ...
def show(*start_urls: str) -> None: ...
def register_eel_routes(app: bottle.Bottle) -> None: ...

def __getattr__(name: str) -> Any: ...
